create table users (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    email varchar(255) not null,
    full_name varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(255) not null check (role in ('USER', 'ADMIN')),
    primary key (id)
);

alter table users
    add constraint uk_users_email unique (email);

create table job_applications (
    id bigint generated by default as identity,
    application_date date,
    company_name varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    job_link varchar(2048),
    job_title varchar(255) not null,
    location varchar(255),
    notes text,
    salary_max numeric(38, 2),
    salary_min numeric(38, 2),
    status varchar(255) not null check (
        status in (
            'APPLIED',
            'ONLINE_ASSESSMENT',
            'INTERVIEW',
            'OFFER',
            'REJECTED',
            'ACCEPTED'
        )
    ),
    updated_at timestamp(6) with time zone not null,
    user_id bigint not null,
    primary key (id),
    constraint fk_job_applications_user
        foreign key (user_id)
        references users (id)
);

create index idx_job_applications_user_id
    on job_applications (user_id);

create table interviews (
    id bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    interviewer_name varchar(120),
    location varchar(120),
    meeting_link varchar(2048),
    notes text,
    scheduled_at timestamp(6) with time zone not null,
    status varchar(255) not null check (
        status in (
            'SCHEDULED',
            'COMPLETED',
            'CANCELLED',
            'RESCHEDULED'
        )
    ),
    type varchar(255) not null check (
        type in (
            'PHONE_SCREEN',
            'TECHNICAL',
            'BEHAVIORAL',
            'ONSITE',
            'FINAL',
            'HR',
            'OTHER'
        )
    ),
    updated_at timestamp(6) with time zone not null,
    application_id bigint not null,
    primary key (id),
    constraint fk_interviews_application
        foreign key (application_id)
        references job_applications (id)
);

create index idx_interviews_application_id
    on interviews (application_id);

create table tasks (
    id bigint generated by default as identity,
    completed boolean not null,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    description text,
    due_at timestamp(6) with time zone,
    title varchar(255) not null,
    updated_at timestamp(6) with time zone not null,
    application_id bigint not null,
    primary key (id),
    constraint fk_tasks_application
        foreign key (application_id)
        references job_applications (id)
);

create index idx_tasks_application_id
    on tasks (application_id);

create table notes (
    id bigint generated by default as identity,
    content text not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    application_id bigint not null,
    primary key (id),
    constraint fk_notes_application
        foreign key (application_id)
        references job_applications (id)
);

create index idx_notes_application_id
    on notes (application_id);
