create table application_status_history (
    id bigint generated by default as identity,
    old_status varchar(255) check (
        old_status in (
            'APPLIED',
            'ONLINE_ASSESSMENT',
            'INTERVIEW',
            'OFFER',
            'REJECTED',
            'ACCEPTED'
        )
    ),
    new_status varchar(255) not null check (
        new_status in (
            'APPLIED',
            'ONLINE_ASSESSMENT',
            'INTERVIEW',
            'OFFER',
            'REJECTED',
            'ACCEPTED'
        )
    ),
    changed_at timestamp(6) with time zone not null,
    application_id bigint not null,
    primary key (id),
    constraint fk_application_status_history_application
        foreign key (application_id)
        references job_applications (id)
        on delete cascade
);

create index idx_application_status_history_application_id
    on application_status_history (application_id);
