create table documents (
    id bigint generated by default as identity,
    name varchar(255) not null,
    type varchar(255) not null check (
        type in (
            'RESUME',
            'COVER_LETTER',
            'PORTFOLIO',
            'OFFER_LETTER',
            'JOB_DESCRIPTION',
            'OTHER'
        )
    ),
    url varchar(2048) not null,
    notes text,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    application_id bigint not null,
    primary key (id),
    constraint fk_documents_application
        foreign key (application_id)
        references job_applications (id)
        on delete cascade
);

create index idx_documents_application_id
    on documents (application_id);
